spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fullSecKil/spring/
          search-paths:
      label: master

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
